export const DISCOVER_CATEGORIES = [
  { id: 'simple', label: 'Simple' },
  { id: 'animal', label: 'Animal' },
  { id: 'mandala', label: 'Mandala' },
  { id: 'people', label: 'People' },
  { id: 'cute', label: 'Cute' },
  { id: 'comic', label: 'Comic' },
  { id: 'food', label: 'Food' },
  { id: 'place', label: 'Place' },
  { id: 'nature', label: 'Nature' },
  { id: 'flower', label: 'Flower' },
] as const;

export type DiscoverCategoryId = (typeof DISCOVER_CATEGORIES)[number]['id'];

const createArtworkList = (category: DiscoverCategoryId, uris: string[]) =>
  uris.map((uri, index) => ({ id: `${category}-${index + 1}`, uri }));

export const DISCOVER_ARTWORKS: Record<DiscoverCategoryId, { id: string; uri: string }[]> = {
  simple: createArtworkList('simple', [
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-1-e38beeb8.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-10-6e176a4c.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-11-ffac3e9c.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-12-04179763.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-13-0edb20b4.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-14-74a74830.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-15-1097fe96.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-16-438815b3.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-17-c657f53f.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-18-1089e661.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-19-e98007cf.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-2-3a4a64f0.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-20-06df1233.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-3-d64e69e4.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-4-b9f006a6.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-5-73c673d0.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-6-e05b31be.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-7-1a5400e8.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-8-d877c275.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/simple/Simple-9-0fb20e01.webp',
  ]),
  animal: createArtworkList('animal', [
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-1-355b3975.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-10-a3581d40.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-11-794c16ea.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-12-a729bb8d.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-13-09d664af.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-14-b530c4c8.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-15-78f60c78.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-16-f113964c.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-17-53a79770.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-18-3ffe58ef.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-19-e36eda2b.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-2-18d2385b.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-20-0ed84273.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-21-83cbca27.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-3-b61db3ad.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-4-99353833.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-5-fafc8479.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-6-bfd654c4.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-7-48aad0d1.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-8-6361a547.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/animal/Animal-9-1807af36.webp',
  ]),
  mandala: createArtworkList('mandala', [
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-1-208e1422.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-10-983541b1.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-11-0a03414f.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-12-7e472f16.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-13-7c485904.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-14-109242a6.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-15-050bfa9e.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-16-253a3f40.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-17-ed1fc575.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-18-43e472ad.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-19-78a2bb13.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-2-d0358cc3.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-20-92beded0.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-3-aef99788.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-4-2ef8fedd.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-5-54cf0c8e.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-6-aeebd1c0.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-7-b4217963.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-8-cbaa3213.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/mandala/mandala-9-166df4c0.webp',
  ]),
  people: createArtworkList('people', [
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-1-8ab5a3b7.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-10-ffcd74d9.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-11-1c38b54a.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-12-a143dda5.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-13-975325a9.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-14-1dff3859.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-15-d018d168.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-16-5ff4afcb.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-17-c3e088fc.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-18-cd9dc1e5.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-19-a5453a61.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-2-39cd31b8.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-20-24003606.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-3-2e5d0d4c.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-4-79ae723a.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-5-1c260ee5.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-6-c088005b.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-7-aaf25e42.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-8-0a93d3d9.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/people/People-9-a52953c4.webp',
  ]),
  cute: createArtworkList('cute', [
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-1-60dd8c4c.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-10-945d2083.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-11-a0e01f04.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-12-ec1d2e8f.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-13-80a6bd04.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-14-bed773f5.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-15-7cbb0c41.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-16-43a37e91.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-17-7e345773.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-18-91890e4e.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-19-22ac6239.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-2-21327699.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-20-d7f05b63.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-3-bba5837f.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-4-925be256.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-5-c73dee0d.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-6-16219885.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-7-cf76ff7e.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-8-0385d8f4.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/cute/Cute-9-4db4f67f.webp',
  ]),
  comic: createArtworkList('comic', [
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-1-7388d74c.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-10-514e431b.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-11-07e31928.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-12-4a087e6f.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-13-edd90c6f.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-14-769c6349.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-15-87add9f3.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-16-8ade72a5.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-17-24a47ba6.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-18-f416d814.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-19-bb788a05.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-2-c8e38644.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-20-5c5c7912.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-3-07b3666d.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-4-962fc202.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-5-adc390f9.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-6-100b2eb6.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-7-2d22d5be.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-8-5498508e.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/comic/Comic-9-fc252284.webp',
  ]),
  food: createArtworkList('food', [
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-1-87b770ad.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-10-c9767798.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-11-6d6248e8.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-12-1417f2b5.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-13-5e7c3598.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-14-63dde0f5.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-15-14231d79.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-2-b375abd9.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-3-19e71963.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-4-98618f73.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-5-fcfae031.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-6-69a806d6.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-7-6ae0dadf.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-8-db3c3598.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/food/Food-9-9d58fa3f.webp',
  ]),
  place: createArtworkList('place', [
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-1-e6007914.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-10-8968af63.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-11-ed58196e.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-12-a5e85762.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-13-879ed46a.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-14-aa22603d.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-15-761c9378.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-2-5fa66e31.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-3-7396cee6.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-4-e7201e7b.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-5-68d2a429.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-6-e1776299.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-7-1cfabfb9.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-8-ec215616.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Places-9-8c9d920c.webp',
  ]),
  nature: createArtworkList('nature', [
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-1-431b8654.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-10-462e3874.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-11-324d141e.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-12-bd9d952a.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-13-90f54c16.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-14-e1443648.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-15-e9472087.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-2-a6d69cc0.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-3-39d0b635.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-4-4262587b.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-5-c09d28dd.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-6-f91cfa7c.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-7-29d74da6.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-8-1a4d9557.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/place/Nature-9-a20b2162.webp',
  ]),
  flower: createArtworkList('flower', [
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-1-f4cef422.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-10-a17edb5d.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-11-4fe9cfd2.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-12-f5b22678.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-13-1b521632.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-14-5b8ec63b.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-15-b4a1e223.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-2-ca0bae6c.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-3-fe8260f7.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-4-25522ec1.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-5-4139f1d8.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-6-01122da0.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-7-eaa5f3e0.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-8-08c62470.webp',
    'https://apps-assets.infinitycorp.tech/public/colorapp/category/flower/Flower-9-60ddadcb.webp',
  ]),
};

export const DEFAULT_DISCOVER_CATEGORY: DiscoverCategoryId = 'simple';

export const getArtworkUris = (categoryId: DiscoverCategoryId) =>
  DISCOVER_ARTWORKS[categoryId].map((artwork) => artwork.uri);
